hash-format = "sha256"

[[files]]
file = "config/MouseTweaks.cfg"
hash = "4069ce1a439d8c37453c1b1e9f2037e0942674c7e48723a39b37eab245792ad4"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "edfe78d985fe67dce28104f3d87673e94c89134144451c291ecedcd2e2c3b480"

[[files]]
file = "config/NoChatReports/NCR-Common.json"
hash = "0eaad2630bd70ade719f7810e805810ada25379269ea194e43d3eea30c51dec0"

[[files]]
file = "config/NoChatReports/NCR-Encryption.json"
hash = "0f61ac30bfc78653a30d715f793e30a6a43d6715106706487efd0aea5d43a84c"

[[files]]
file = "config/NoChatReports/NCR-ServerPreferences.json"
hash = "df32843b853e0a493ef3a9b1e39276818294353fbb0d833f7f61e77da0f5bca1"

[[files]]
file = "config/NoChatReports/README.md"
hash = "c52b76ccad2bd1063a22c7f6bb9e7c5db6b00fb53a6fd605585972ee0e5fc01f"

[[files]]
file = "config/aiimprovements-common.toml"
hash = "99113ed20833ab95be2a9ca46ffc88e3427b066d4b02646873cdebe2203fd622"

[[files]]
file = "config/alltheleaks.json"
hash = "a7257d34565cbec7365e353a3fe8ea3abc09ad924eb3c0c64aa04cf47e5ede66"

[[files]]
file = "config/badoptimizations.txt"
hash = "cae5ba66971b2f61e0b523c5aeb8b8d4fa806f0bea8a1709860e4fea94426ac9"

[[files]]
file = "config/balm-client.toml"
hash = "9923b77b07293c6ae5363fde993daa3597423ded51756528d2830c01a5f716ea"

[[files]]
file = "config/balm-common-1.toml.bak"
hash = "9bc57add9cde46b46ac4d8c1f9006280721750e5df6cca2439b9b750e83c9e46"

[[files]]
file = "config/balm-common.toml"
hash = "9ddede6cc42a2370eb16af7132d56138ca83357c74b4079b6ed4c885d4b46841"

[[files]]
file = "config/betterf3.toml"
hash = "1a8d0c828599473af0f926c1660a8a58dd2b1122acf034a7aac489cb88317ab1"

[[files]]
file = "config/betterfpsdist.json"
hash = "7410aa05bb28180a3d5389fe955affffa7e7842e330385d042eb78e7a73db017"

[[files]]
file = "config/catalogue.properties"
hash = "9355d649d8f41a9b3151cc721aae1def21ce6683dac181166ea230288f463d57"

[[files]]
file = "config/catalogue_favourites.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/chunksending.json"
hash = "e589c5988aa0f23e08400df47ef156a61eea1978f2161ba014da278c28a60ac7"

[[files]]
file = "config/chunky/config.json"
hash = "6c103db0800e63ba88c2296e42fb8f5e631f70ea17b8c5d77bef0166d0662d96"

[[files]]
file = "config/connectivity.json"
hash = "6b95731807c56659d67f5c439439493834d0c42ad33baf23ef60d45bb7e73202"

[[files]]
file = "config/cupboard.json"
hash = "08bda8a4a20d302cb97d06bf11c4991e152a3a9e04c17302ea3b42aa77e6b028"

[[files]]
file = "config/defaultoptions-common.toml"
hash = "7f84b4d37e39956dd57ed232b08453ea3c2c4578bdf1430d42b4e77a15024b75"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "90760da79853eaf33c79d9e7c0599900447848caa9940e2ee9cf80f4ff23b0ff"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "257392973f0a4b5b3577b144ee4202ba11761857d241588000e390eaa95c57cd"

[[files]]
file = "config/dynamic_fps.json"
hash = "ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356"

[[files]]
file = "config/entity_model_features.json"
hash = "d0fc40ba86b8af64f5c27c8c5b3284a5021cd97131e65ca645d64f2421529656"

[[files]]
file = "config/entity_texture_features.json"
hash = "0554c0e7816266477c65c18d2ada9fdddf1c6750787efd329056223ca4a073b2"

[[files]]
file = "config/entityculling.json"
hash = "c5685d30d087224750a826e44364738e4e45e407d7837459a6069d08ebbcef2b"

[[files]]
file = "config/etf_warnings.json"
hash = "a5ba22e63061c1fb67f0f895f17681351eaeccc225faef966c29ee630593275e"

[[files]]
file = "config/euphoria_patcher.properties"
hash = "45f29fcdee25c1e7c5196524aca8555743672792a29fb0d7a9343d47b890c8e6"

[[files]]
file = "config/fastpaintings-common.toml"
hash = "d0b4c0e85822735c3cc9800108204225e1f8e4fd17a17fff9ecfd4ab045e5f03"

[[files]]
file = "config/ferritecore-mixin.toml"
hash = "7724615b78b3aada388fe595c05f6a3b9807e069f1aaf70c332e991434c45e57"

[[files]]
file = "config/fml.toml"
hash = "bc1caed4bead0b5bb54755dc11f8283cc472b780db39e571e80723dacbb37ae2"

[[files]]
file = "config/immediatelyfast.json"
hash = "f2b7f219198f0a911d04b09f545f2c1256e8d114951443924878dc10963e16aa"

[[files]]
file = "config/iris-excluded.json"
hash = "4d3264b58c502afaeca3f44e8d2db0843c54b8ba957afd21a2d450fe10dafefb"

[[files]]
file = "config/iris.properties"
hash = "c363e033d38a4461bda4b4bc1179045607fd27c4dd914643b5cee2d441961089"

[[files]]
file = "config/leaky.json"
hash = "ee5d331e53643f4fe05a9bd42f30da19efe4b1e9cac68aae76da30635bf4004e"

[[files]]
file = "config/limitedchunks.json"
hash = "1a5929cfa7c9ad1b2842fd5ea9aa0d107785a1d4b9e92ba62ffac9e3f7245947"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/modernfix-common.toml"
hash = "72ca2bcea2a9946a3a54842f14eff6f7b47d8fc96ef497c1b56406643b153fd7"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "622658ab12d4c1b249b8fcbe1ec68b7424a66b45ddb1e52f447e690c23d1d960"

[[files]]
file = "config/monolib-common.toml"
hash = "2221dd3c477459743492fd042d5f06f58c40af18cd5f40824245a15c79daf4c1"

[[files]]
file = "config/monolib.toml"
hash = "11b3fe61174f04061e20dea7fb3bd4615f6e98777de64292a86f4d7acf168adf"

[[files]]
file = "config/moonlight-client-1.toml.bak"
hash = "10a4552c3c8129bee227f8e72396b7c7eb2f67a4fc20649d9320381b6ad66c8b"

[[files]]
file = "config/moonlight-client-2.toml.bak"
hash = "6504dc07b5028b68d3e7a2680b0c188f12b794fc6eee8053d572e9640dd13472"

[[files]]
file = "config/moonlight-client.toml"
hash = "019862421c02c0362e2bb02766f08d37571a6d21d25dff883e3916800394c8b2"

[[files]]
file = "config/moonlight-common-1.toml.bak"
hash = "2c96ee208128b6338b54eb3aa62b2f378199e452daaa76e4a40f1d4d62b4c33e"

[[files]]
file = "config/moonlight-common-2.toml.bak"
hash = "6eacdb4c76215925e8df2505bb9a3cf582ba2177310212c8f372dc50c49c94d8"

[[files]]
file = "config/moonlight-common-3.toml.bak"
hash = "6ae9ec9348bd85d9d67c401536fc13dd0ae72760438ec915a0c18c0627dcae07"

[[files]]
file = "config/moonlight-common.toml"
hash = "41db18994508f305093eb8a1d6ebd18c7d1b6560068318cbd7e60465d3b4f631"

[[files]]
file = "config/neoforge-client.toml"
hash = "d58d93e2c429410d0abf25507d1679f732e1023b03bb52414348efcf5cf3ddb0"

[[files]]
file = "config/neoforge-common.toml"
hash = "fe878a2717a145cd890621eac5b3be1e1fd656f7ff9abc6e8d53f670d37474c4"

[[files]]
file = "config/neoforge-server.toml"
hash = "b1e3b38d612295f8d9dfa0fbdb538a992b7a1a3b7a766c491b4e9fdf3823396f"

[[files]]
file = "config/neruina.json"
hash = "29e73ae1075a5d9f61394a353e60ba84c5c801e511105f2400e0d4ba66a9bf76"

[[files]]
file = "config/placebo.cfg"
hash = "eb7e9906d126543f03c2257ca98efa4b845d1e7479dc8b069a12b194c86debcf"

[[files]]
file = "config/recipeessentials.json"
hash = "96b6764c28555977f3f2f7091b881de3c3def4560584ac13a1c42b6c692a6755"

[[files]]
file = "config/smoothchunk.json"
hash = "5f85b2c857c2561cf720745f724d20befce7bb58732083259a798263c0af99f2"

[[files]]
file = "config/sodium-extra-options.json"
hash = "f614f1e1ebf5e598068f456ec333e6417b9836ffbc94e386aa0a434319734da9"

[[files]]
file = "config/sodium-extra.properties"
hash = "a2f1b47c1eaa119ab34727f1d43c2506cb3d7f17ba8fb4efb49e20c8e0b58e70"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "1acd3c330fd5edb7f588f6d7208f1d6c676a7b69e80a1739458f0de75469f3af"

[[files]]
file = "config/sodium-mixins.properties"
hash = "8939df3a10627cf3b9a3cc0e2824337923e9a26d11e60f5a1f7c0cfbd171a574"

[[files]]
file = "config/sodium-options.json"
hash = "be40d116c4d2eff2e12e2ebd811a6c365955acbfed39361cef22cbd23e0dd74f"

[[files]]
file = "config/sodiumextras-client.toml"
hash = "ddd8950d7d4c21a8bb2761a196ffb397a2d3b65fe293aa0938b7a381b196cdee"

[[files]]
file = "config/startinv.json"
hash = "dec33c239556bb7bbdee1914959330b480422a820f33bfad09489c5a6d3943e6"

[[files]]
file = "config/structureessentials.json"
hash = "54826c1ce55156e6a3d19a22949d733668806c7ed4a77218cc1d26bb6c5fa7bd"

[[files]]
file = "config/time_on_display.toml"
hash = "3ab3a842d6ee3cf8f2e5a5975f46a01db553ca6111249ccea96206ea0cd6dabf"

[[files]]
file = "config/toastcontrol-client-1.toml.bak"
hash = "ff3f64666b3457189fb3e7ba44d7a05f61e069b0fec41d2ad2ade63fbbd73a7d"

[[files]]
file = "config/toastcontrol-client.toml"
hash = "633a90a36cf0947b199e9a6737c19982d8130820a18b69aa0d16240b584ec001"

[[files]]
file = "config/transition.json"
hash = "6c0060c7301372bbc414f86a139b383e34fb620f0621badd71bb19efc3f26767"

[[files]]
file = "config/trender.json"
hash = "0a282f3623f7f9443a1d10b5768865f69e58b74e000dcfb4f40399626b7a6124"

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "db026135a8a23b2b660ebbfa8a85d06b26249305b2612bc2fab930e252100890"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "49dedd58a30df8112ca9922789f05726a7775fdc58ef626b05894aad8cfcbea0"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "571293a6ddb6b5ea7b9c1f5454d0cfc584a5aa50397942bea4906d3b54e02e02"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e2f2a6f6ff38054ce8d91a43a20b79ea7b4e84cb924142fb7d2bcfdd95fe5b57"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "e587e79637fbc8dc23f29d51e2c4a685a3bcfbdb28b24452620dedbab8e7368c"
metafile = true

[[files]]
file = "mods/better-fps-render-distance.pw.toml"
hash = "422e9de11c4996c14a0a907cfe627428c7c52e9ee55c8da0193236038da02680"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "c495c19a48e96ad7d32d8738a9209539968f7f41db7a5f8d20eed1b0f477fcad"
metafile = true

[[files]]
file = "mods/catalogue.pw.toml"
hash = "98db626859ef290e5f7be9084d9f8a4b93ef441a8762ff08cebcf36308b36225"
metafile = true

[[files]]
file = "mods/chunk-sending-forge-fabric.pw.toml"
hash = "5488558b52cdbacdc991c1f76b658c49a3c40f53ddf49a22df988d516bcdcfc7"
metafile = true

[[files]]
file = "mods/chunky-pregenerator-forge.pw.toml"
hash = "7be63eaec6a70605f2f21cc30f0889fb27978c2e2fe62ee4584210502289e77d"
metafile = true

[[files]]
file = "mods/client-crafting.pw.toml"
hash = "1f41272b5cdabe73dc343bdb89eb9993c82df611a18182dcbc7107a46b7458bb"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "22286fa216349c0767808903a0a38662857d2adee54950a18cbf26c167a06029"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2e6a2f8c477128a76ef059dfef7ca8a1befa2ae0ebe7ae2171e716f0c905cd00"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "81105a1a363873f3675a861d228abcf0f2a8356f1a17850c06f6d6c47e454634"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "42ffb6f5835250003da6ca3667ff751709ea295faee43b49c365b0f6c1e8f4d8"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "92d8711662b4e3fd42a57254571aca9f0b33a10bb7492a8fba59b22e78f688e6"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "539513ed35cebfaa099397dde2d1936d38489c8685e96a902211f60cecee82c4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4fa1d6b802032c2335bd0f2263e2977b376fd22ee07dc5f57dae9797d0c267d3"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "0f6c676be62bc696e11fc14a01f4e193e78e4f395ad5b03e771ea9fba81e9f97"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "4ca4a4c7f9980e890449d743322cb9eaac944909a91c502ff3bdf82393826d0a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "18e03661898661bb4434f28c838cbd1ca610c2db9ecd78fc698830bea90e8341"
metafile = true

[[files]]
file = "mods/fast-async-world-save-forge-fabric.pw.toml"
hash = "c19754832997fe5fbd9488eeb3b02f3221f36893f94003e403b731ed9e9132ce"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "5961d4df1656f866ef9f003093d822e7396db716064c1d44bb30e8936de6ce88"
metafile = true

[[files]]
file = "mods/fast-paintings.pw.toml"
hash = "0f871a463cc9f10ba812d7e7cbdbfb119535d1a683c8eb85d06af35d7c726953"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/fix-gpu-memory-leak.pw.toml"
hash = "e70c20bf24819da470d25d8cfe9cd07d2fc4ace4de942e7bcd38f7a674a24b6c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6c275f621e7c3895ed34ee0e5bf847916a4285ac0f6452982ad6dccd5dd59851"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "352bbd56bffa7bb7af6e16ae0e745db85e2d7e9e0ea6037ff866149f6e6e08b8"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "e8ad4c0b1a01858f6d653672472641f24aeacf7d6fb3b63a4358157312381a76"
metafile = true

[[files]]
file = "mods/leaky.pw.toml"
hash = "62574e74c238814dee84398b1caa0f19f7e3f381041b4f17cb1853815047ab5d"
metafile = true

[[files]]
file = "mods/limited-chunkloading.pw.toml"
hash = "fb88337b7840e3c06138a63aca65fbaedf6bb8aaca6fd91bc8154d3c27db7846"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3ac8c76f4cb2f1200d60fa2e74108d9cb9355346ddb8a4a735134dfac7b77136"
metafile = true

[[files]]
file = "mods/magnesium-extras.pw.toml"
hash = "af6b190e42b601eb0e2ca6fd58209f0242ab8c403996f1814956a6699dcd4f86"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "4acb02c7e590ebb510be417e6269e7f07c7b650cf95080cab0daa3005cc8c919"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "97521b85e74dfbc642b9102a46be0cdda07b9cfe36aba027a3878054f93ccfcb"
metafile = true

[[files]]
file = "mods/monolib.pw.toml"
hash = "4387cfb8d69490641337ec3d42a8a434683a2d2b129990705e78a800f2795ad1"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "2bdee19bd39b4bd411d7c858a7978ca9d2bdda41c1cf15920ea6be0014663f79"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "26aca541ff9f149ef8bfdf69efb258d23339affd9fba4612bddd01e759fb0ffd"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "201e0be56d2d9430843688b4a04dea207732b6d60f8001fb9e6396d48aea287f"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8b725f1822c0feab9e51bef600f2ee6f4c26efbb55aa3ee9073a027f1f134202"
metafile = true

[[files]]
file = "mods/redirected.pw.toml"
hash = "a8e09044fb84c6b63782d68be84c899fbecebf7b70ee3f36a83bcff9e475d411"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "6a48780ffd4bc3b941f81232c84034aba5ff7645ea635c604de6df71e6596bb3"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6c0fac550bb053ee2728144a28819835823dcc6d04ad7897750431fe55100e53"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "6614ee56bd8eeae972736f605434c394f929a6874c16d9254e83dcd627a1a6b3"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
hash = "ff6934dbf3203c63dbdab3b2b3a89e82c047ad22db63d8511d737a489aac743c"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "05953528b550760efecc9834796d90177e09bd0d231ce814b43578e386468a73"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "6d9eaf43c14c66465e87bf03cc5cb5ecef57b3f2e8063c52f6332d33689d30be"
metafile = true

[[files]]
file = "mods/startinv.pw.toml"
hash = "4318e9916b0168dad46b26b007e9f986fc27f72099bbcb99222f8fa7d5d34a27"
metafile = true

[[files]]
file = "mods/structure-essentials-forge-fabric.pw.toml"
hash = "506c793ef226a2a774b7f7ec830745926eea7cbcf660cf0b7440823fffdc1bf2"
metafile = true

[[files]]
file = "mods/time-on-display.pw.toml"
hash = "c90a1540ee877c337ad39079fd2e36a16e6bf1b768f8598938baf0eb9dce0422"
metafile = true

[[files]]
file = "mods/toast-control.pw.toml"
hash = "29d1e04030fcbdad4ee91eb9bc0b0d6b8907ffe967c9bd0543e8bb7e3dab5282"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
hash = "7d7deb14e956b71fe2f9c999acefdb5edbfc264d9c66e5e2fce7c90ee704d05a"
metafile = true

[[files]]
file = "mods/yeetusexperimentus.pw.toml"
hash = "7c6f2e38a6932f846738747fd6cff3af239748a84e89350f6c967c8ac72a65d6"
metafile = true
