name = "KenkuKraft"
author = "furglitch"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e950bb76f7526ba508271dd2c9709938c664ac466a573e54a18667a750f474e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
