["Day Counter Overlay Settings"]
	showDayOverlay = true
	showOverlayAlways = true
	dayOverlayX = 0.00625
	dayOverlayY = 0.015

["Death Counter Self Settings"]
	showDeathSelfOverlay = true
	showSelfOverlayAlways = true
	deathSelfX = 0.00625
	deathSelfY = 0.122

["Coordinates Overlay Settings"]
	showCoordsOverlay = false
	showCoordsOverlayAlways = false

["Ping Settings"]
	showPingAsText = true

["Emote Settings"]
	showEmojis = false
