[magic]
	[magic.abilities]
		save_all_abilities = true

[dragon_hunters]
	pillager_experience_gain = 4
	pillage_cooldown = 6000
	max_pillage_render_distance = 32
	trapped_effect_duration = 5.0

[growth]
	save_growth_stage = true

[general]
	retain_claw_items = false
	start_with_dragon_choice = false
	transform_altar = true
	allow_dragon_choice_from_inventory = true
	no_humans_allowed = false

[ender_dragon]
	ender_dragon_curses_you = true