autoReloadEnabled = "CREATIVE"
armsDealerHouse = 2
itemDropChance = 0.5
maxItemDropCount = 32
bulletsBreakGlassEnabled = true
headshotDamageModifier = 3.0
goreEnabled = true
advancedIrisIntegrationEnabled = true
firstPersonAnimationsEnabled = true
thirdPersonAnimationsEnabled = true