	[renderers.inventory_renderer]
		max_columns = 4
		max_rows = 4
		scale = 4.0
		screen_side = "LEFT"
		renderer_type = "GUI_COMPACT"
		effects_everywhere = false

	[renderers.gui_renderer]
		max_columns = 4
		max_rows = 4
		scale = 4.0
		screen_side = "RIGHT"
		renderer_type = "GUI_COMPACT"
		offset_x = 80
		offset_y = 6