noSolicitingEnabled = true
noSolicitingChunkRangeBanner = 8
noSolicitingChunkRangePlayer = 8
noSolicitingChunkRangeCarpet = 8
noRaiderEnabled = false
additionalGrowthHeight = 8
additionalGrowthTicks = 8
betterSleepEnabled = false

noTramplingEnabled = false