name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "522a23cc5c2121cd4fdd6546711f4c147a80eba805c54b8988acfc3351939fe4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
