name = "KenkuKraft"
author = "furglitch"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb595a309f01138374f4662d99dc17d1b6b7bea6f9a6eee6e59ad7e0dd9ebf47"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
