name = "KenkuKraft"
author = "furglitch"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "793117cc95c77c210856962689adfa490a174950ab7d0678785bbceafd481cf9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
