name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "429f26b457309247fcb041ae86407d41ce2c02d5ca0c03a48af3948e90c53fa2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
