name = "KenkuKraft"
author = "furglitch"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9260bb5878e2eddf70db564fd9fd04330c1e9b662cfcace07e4ccfcf84a37fd3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
