name = "KenkuKraft"
author = "furglitch"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5eaa4a1551ec61c4d3f594ec63cbdee3205178b37d3ddc353ec9dd38f8fddbb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
