name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e2e81b24e266bac517ed789a3b75f91d2d399ac07ed3b34ba5ef882ea897378"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
