name = "KenkuKraft"
author = "furglitch"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84a2297ebe31d0e6ee5e57517b40eb448a95e7b46d3885f863443a9ecb4a3347"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
