name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c74b859bf58655ed3bf87a9def3d55a6e9d2aea4c76a8cd05597b144a5a8accf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
