name = "KenkuKraft"
author = "furglitch"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc52a0fb4bc91a7374f96f6bc3b3866156666b5f549d3642504b75e63d613230"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
