name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae8d228feb4f8380a198c5e5a57a60b2badfb13f699b8b21970efcccee5c1b83"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
