name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c33921a4eef487a09dd738e36e8d8f6b11cd1967eec366ad97b2242796e674a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
