name = "KenkuKraft"
author = "furglitch"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f2546e7f65cb2265248139438d4b9f7e2f3082066cc19ca250a24825fdd60d1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
