name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b9230f98d10fd11558672c34a07a1f76d76704b5905dc19b257f004a96e929a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
