name = "KenkuKraft"
author = "furglitch"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07a0aaa9cefd959be750cdeca2707e433cadc35fca92fc124f3bfe3f0943cb65"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
