name = "KenkuKraft"
author = "furglitch"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5533a6cd2e39ee39d947e6b368026f637b57b98126598cb506e8157f9c4f00dd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
