name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98ed7f87ef7a2ec176e955324cb87f21ce9730f8c933c189fa712e307ef93f54"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
