name = "KenkuKraft"
author = "furglitch"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c841d22f1b7fae2761fbafc06bbfbf403d8818a5560287430a18170f087e1ebf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
