name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b057c6d72f9cf8b3d2a6dd2a78b7c2baf4c76fb73808e74849298d2762ea856"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
