name = "KenkuKraft"
author = "furglitch"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa15fa0b9f006290cf2a0aa6ba701b3fa1bc9a8253ed809ed1fe6b185ccf0ea5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
