name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07ae733be4dcfc7965befc96542de65c8946320633f458d0a1e0ba44c93462cd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
